import pyperclip

# this module allows access to the clipboard for copying and pasting into/out of programs

dec = "The United States Declaration of Independence, formally The unanimous Declaration of the thirteen united States of America, is the pronouncement adopted by the Second Continental Congress meeting in Philadelphia, Pennsylvania, on July 4, 1776. Enacted during the American Revolution, the Declaration explains why the Thirteen Colonies at war with the Kingdom of Great Britain regarded themselves as thirteen independent sovereign states, no longer under British rule. With the Declaration, these new states took a collective first step in forming the United States of America. The declaration was signed by 56 of America's Founding Fathers, congressional representatives from New Hampshire, Massachusetts Bay, Rhode Island and Providence Plantations, Connecticut, New York, New Jersey, Pennsylvania, Maryland, Delaware, Virginia, North Carolina, South Carolina, and Georgia. The Declaration became one of the most circulated and widely reprinted documents in early American history The Lee Resolution for independence was passed by the Second Continental Congress on July 2 with no opposing votes. The Committee of Five had drafted the Declaration to be ready when Congress voted on independence. John Adams, a leader in pushing for independence, had persuaded the committee to select Thomas Jefferson to compose the original draft of the document,[2] which Congress edited to produce the final version. The Declaration was a formal explanation of why Congress had voted to declare independence from Great Britain, more than a year after the outbreak of the American Revolutionary War. Adams wrote to his wife Abigail, The Second Day of July 1776, will be the most memorable Epocha, in the History of America;[3] although Independence Day is actually celebrated on July 4, the date that the wording of the Declaration of Independence was approved. After ratifying the text on July 4, Congress issued the Declaration of Independence in several forms. It was initially published as the printed Dunlap broadside that was widely distributed and read to the public. The source copy used for this printing has been lost and may have been a copy in Thomas Jeffersons hand.[4] Jeffersons original draft is preserved at the Library of Congress, complete with changes made by John Adams and Benjamin Franklin, as well as Jeffersons notes of changes made by Congress. The best-known version of the Declaration is a signed copy that is displayed at the National Archives in Washington, D.C., and which is popularly regarded as the official document. This engrossed copy (finalized, calligraphic copy) was ordered by Congress on July 19 and signed primarily on August 2.[5][6]"

pyperclip.copy(dec)


